CREATE TABLE "ROLE" (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL UNIQUE,
    description VARCHAR
);
CREATE TABLE APP_USER (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL,
    username VARCHAR NOT NULL UNIQUE,
    password_hash VARCHAR NOT NULL,
    first_name VARCHAR NOT NULL,
    last_name VARCHAR NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_app_user_role
        FOREIGN KEY (role_id) REFERENCES "ROLE" (role_id)
);

CREATE TABLE MATERIAL_TYPE (
    material_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    description VARCHAR,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP
);

CREATE TABLE CNC_MACHINE (
    cnc_machine_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    manufacturer VARCHAR,
    model VARCHAR,
    controller VARCHAR NOT NULL,
    work_area_x DOUBLE PRECISION NOT NULL,
    work_area_y DOUBLE PRECISION NOT NULL,
    work_area_z DOUBLE PRECISION,
    max_feed_rate DOUBLE PRECISION,
    min_spindle_speed DOUBLE PRECISION,
    max_spindle_speed DOUBLE PRECISION,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE TOOL (
    tool_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cnc_machine_id BIGINT NOT NULL,
    tool_number INTEGER NOT NULL,
    name VARCHAR NOT NULL,
    type VARCHAR,
    diameter DOUBLE PRECISION NOT NULL,
    cutting_length DOUBLE PRECISION,
    flute_count INTEGER,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_tool_cnc_machine
        FOREIGN KEY (cnc_machine_id) REFERENCES CNC_MACHINE (cnc_machine_id),
    CONSTRAINT uq_tool_machine_number
        UNIQUE (cnc_machine_id, tool_number)
);

CREATE TABLE MATERIAL_SHEET (
    material_sheet_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_type_id BIGINT NOT NULL,
    width DOUBLE PRECISION NOT NULL,
    height DOUBLE PRECISION NOT NULL,
    thickness DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_material_sheet_material_type
        FOREIGN KEY (material_type_id) REFERENCES MATERIAL_TYPE (material_type_id)
);

CREATE TABLE MACHINING_PARAMETERS (
    machining_parameters_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spindle_speed DOUBLE PRECISION NOT NULL,
    feed_rate DOUBLE PRECISION NOT NULL,
    plunge_rate DOUBLE PRECISION NOT NULL,
    cut_depth DOUBLE PRECISION NOT NULL,
    step_down DOUBLE PRECISION NOT NULL,
    safe_z DOUBLE PRECISION NOT NULL
);

CREATE TABLE SHAPE (
    shape_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shape_type VARCHAR NOT NULL,
    shape_subtype VARCHAR,
    dimension_a DOUBLE PRECISION NOT NULL,
    dimension_b DOUBLE PRECISION,
    dimension_c DOUBLE PRECISION,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP
);

CREATE TABLE MACHINING_JOB (
    machining_job_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by_user_id BIGINT NOT NULL,
    cnc_machine_id BIGINT NOT NULL,
    tool_id BIGINT NOT NULL,
    material_sheet_id BIGINT NOT NULL,
    machining_parameters_id BIGINT NOT NULL,
    shape_id BIGINT NOT NULL,
    name VARCHAR NOT NULL,
    quantity INTEGER NOT NULL,
    g_code CLOB NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_machining_job_created_by
        FOREIGN KEY (created_by_user_id) REFERENCES APP_USER (user_id),
    CONSTRAINT fk_machining_job_cnc_machine
        FOREIGN KEY (cnc_machine_id) REFERENCES CNC_MACHINE (cnc_machine_id),
    CONSTRAINT fk_machining_job_tool
        FOREIGN KEY (tool_id) REFERENCES TOOL (tool_id),
    CONSTRAINT fk_machining_job_material_sheet
        FOREIGN KEY (material_sheet_id) REFERENCES MATERIAL_SHEET (material_sheet_id),
    CONSTRAINT fk_machining_job_parameters
        FOREIGN KEY (machining_parameters_id)
        REFERENCES MACHINING_PARAMETERS (machining_parameters_id),
    CONSTRAINT fk_machining_job_shape
        FOREIGN KEY (shape_id) REFERENCES SHAPE (shape_id),
    CONSTRAINT uq_machining_job_material_sheet UNIQUE (material_sheet_id),
    CONSTRAINT uq_machining_job_parameters UNIQUE (machining_parameters_id),
    CONSTRAINT uq_machining_job_shape UNIQUE (shape_id),
    CONSTRAINT chk_machining_job_quantity CHECK (quantity > 0)
);
