ALTER TABLE CNC_MACHINE ALTER COLUMN work_area_z DROP NOT NULL;
ALTER TABLE CNC_MACHINE ALTER COLUMN max_feed_rate DROP NOT NULL;
ALTER TABLE CNC_MACHINE ALTER COLUMN min_spindle_speed DROP NOT NULL;
ALTER TABLE CNC_MACHINE ALTER COLUMN max_spindle_speed DROP NOT NULL;
